<!DOCTYPE html>
<html lang="es">

	<?php include "../templates/layouts/head.php"; ?>

	<body>
		<?php include "../templates/layouts/header.php";  ?>
		<?php include "../templates/layouts/menu.php"; ?>


	<section id="main-content">
      <section class="wrapper smain-chart" >
        

        <div class="row mt">
            <div class="col-md-12 col-sm-12 mb">
                <div class="message-p ">

                    <div class="message-header">
                       
                        <span class=" fa fa-user fa-2x pull-left" style="padding-left: 10px; padding-top: 5px;"></span>
                        <button type="button" class="btn btn-info pull-right" data-toggle="modal" data-target="#myModal">Agregar <i class="fas fa-plus"></i></button>
                        <h5>USUARIOS</h5>
                        
                    </div>
                    <div style="padding: 10px;">
                    <input type="text" name="table_search" id="search" class="form-control" placeholder="DNI, Nombre y Apellidos" >

                    <table class="table table-bordered table-striped table-condensed p-3">
                        <caption></caption>
                        <thead>
                            <tr>
                                <th>header</th>
                                <th>header</th>
                                <th>header</th>
                                <th>header</th>

                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>data</td>
                                <td>data</td>
                                <td>data</td>
                                <td><a data-toggle="tooltip" data-placement="top" data-modify="" title="modificar" style="margin-right:5px" class="modify btn btn-primary btn-sm" href="#" id="modify'+cont+'"><i style="color:#fff" class="fas fa-edit"></i></a><a data-toggle="tooltip" data-index="" data-placement="top" title="eliminar" style="margin-right:5px" class="delete btn btn-danger btn-sm" href="#"><i style="color:#fff" class="fas fa-trash-alt"></i></a></td>
                            </tr>
                            <tr>
                                <td>data</td>
                                <td>data</td>
                                <td>data</td>
                                <td><a data-toggle="tooltip" data-placement="top" data-modify="" title="modificar" style="margin-right:5px" class="modify btn btn-primary btn-sm" href="#" id="modify'+cont+'"><i style="color:#fff" class="fas fa-edit"></i></a><a data-toggle="tooltip" data-index="" data-placement="top" title="eliminar" style="margin-right:5px" class="delete btn btn-danger btn-sm" href="#"><i style="color:#fff" class="fas fa-trash-alt"></i></a></td>
                            </tr>
                            <tr>
                                <td>data</td>
                                <td>data</td>
                                <td>data</td>
                                <td><a data-toggle="tooltip" data-placement="top" data-modify="" title="modificar" style="margin-right:5px" class="modify btn btn-primary btn-sm" href="#" id="modify'+cont+'"><i style="color:#fff" class="fas fa-edit"></i></a><a data-toggle="tooltip" data-index="" data-placement="top" title="eliminar" style="margin-right:5px" class="delete btn btn-danger btn-sm" href="#"><i style="color:#fff" class="fas fa-trash-alt"></i></a></td>
                            </tr>
                            <tr>
                                <td>data</td>
                                <td>data</td>
                                <td>data</td>
                                <td><a data-toggle="tooltip" data-placement="top" data-modify="" title="modificar" style="margin-right:5px" class="modify btn btn-primary btn-sm" href="#" id="modify'+cont+'"><i style="color:#fff" class="fas fa-edit"></i></a><a data-toggle="tooltip" data-index="" data-placement="top" title="eliminar" style="margin-right:5px" class="delete btn btn-danger btn-sm" href="#"><i style="color:#fff" class="fas fa-trash-alt"></i></a></td>
                            </tr>
                            <tr>
                                <td>data</td>
                                <td>data</td>
                                <td>data</td>
                                <td><a data-toggle="tooltip" data-placement="top" data-modify="" title="modificar" style="margin-right:5px" class="modify btn btn-primary btn-sm" href="#" id="modify'+cont+'"><i style="color:#fff" class="fas fa-edit"></i></a><a data-toggle="tooltip" data-index="" data-placement="top" title="eliminar" style="margin-right:5px" class="delete btn btn-danger btn-sm" href="#"><i style="color:#fff" class="fas fa-trash-alt"></i></a></td>
                            </tr>
                            <tr>
                                <td>data</td>
                                <td>data</td>
                                <td>data</td>
                                <td><a data-toggle="tooltip" data-placement="top" data-modify="" title="modificar" style="margin-right:5px" class="modify btn btn-primary btn-sm" href="#" id="modify'+cont+'"><i style="color:#fff" class="fas fa-edit"></i></a><a data-toggle="tooltip" data-index="" data-placement="top" title="eliminar" style="margin-right:5px" class="delete btn btn-danger btn-sm" href="#"><i style="color:#fff" class="fas fa-trash-alt"></i></a></td>
                            </tr>
                            <tr>
                                <td>data</td>
                                <td>data</td>
                                <td>data</td>
                                <td><a data-toggle="tooltip" data-placement="top" data-modify="" title="modificar" style="margin-right:5px" class="modify btn btn-primary btn-sm" href="#" id="modify'+cont+'"><i style="color:#fff" class="fas fa-edit"></i></a><a data-toggle="tooltip" data-index="" data-placement="top" title="eliminar" style="margin-right:5px" class="delete btn btn-danger btn-sm" href="#"><i style="color:#fff" class="fas fa-trash-alt"></i></a></td>
                            </tr>
                            
                        </tbody>
                    </table>

                    </div>
                </div>

            </div>
            
        </div>

       
      </section>
    </section>
            <?php include "modal/modalUsuario.php"; ?>
		<?php include "../templates/layouts/scriptfinal.php"; ?>
	</body>
	
</html>