<?php
	if (isset($_SESSION["logged_is_user"])) {
	    if ($_SESSION["role"] === "AD") {
	        header("Location: http://localhost:8080/SPV/public/articulo");
	    } else if ($_SESSION["role"] === "RE"){
	    	header("Location: http://comedor.undac.edu.pe:8094/reporte1");
	    } else if ($_SESSION["role"] === "BU"){
	    	header("Location: http://comedor.undac.edu.pe:8094/reporte1");
	    } else{
	        header("Location: http://comedor.undac.edu.pe:8094/novedades");
	    }
	    exit();
	}
?>




<!DOCTYPE html>
<html lang="es">

<?php include "../templates/layouts/head.php"; ?>
<body>
  <!-- **********************************************************************************************************************************************************
      MAIN CONTENT
      *********************************************************************************************************************************************************** -->

  <div id="login-page">
    <div class="container">
      <div class="row">
        <div class="col-md-6 align-items-center justify-content-center">
            <!--<img src="img/instagram.jpg" alt="" width="50" height="50">-->
      
          </div>
        <div class="col-md-6">
          <form class="form-login" id="login">

            <h2 class="form-login-heading">INICIAR SESIÓN</h2>
            <div class="login-wrap">
              <select class="form-control" id="gradoAcad"   name="role" type="select" autofocus>
                <option value="" disabled="true" selected="true">-- Seleccione Rol --</option>
                <option value="AD">Administrador</option>
                <option value="VE">Vendedor</option>
                <option value="SI">Sistema</option>
              </select>
              <br>
              <input type="text" name="user" class="form-control" placeholder="Usuario/DNI" >
              <br>

              <input type="password" name="password" class="form-control" placeholder="Clave">
              <!--<label class="checkbox">
                <input type="checkbox" value="remember-me"> Remember me
                <span class="pull-right">
                <a data-toggle="modal" href="login.html#myModal"> Forgot Password?</a>
                </span>
                </label> -->
                <br>
              <button class="btn btn-theme btn-block" type="submit" value="gfjghjf"><i class="fa fa-lock"></i> INGRESAR</button>
              <hr>
              <!--<div class="login-social-link centered">
                <p>or you can sign in via your social network</p>
                <button class="btn btn-facebook" type="submit"><i class="fa fa-facebook"></i> Facebook</button>
                <button class="btn btn-twitter" type="submit"><i class="fa fa-twitter"></i> Twitter</button>
              </div>
            -->
              
              <!--<div class="registration">
                Don't have an account yet?<br/>
                <a class="" href="#">
                  Create an account
                  </a>
              </div>-->
              <div class="messaje" role="alert">

                </div>
            </div>
            <!-- Modal -->
         
            <!-- modal -->
          </form>
        </div>
      </div>
      
    </div>
  </div>
  <!-- js placed at the end of the document so the pages load faster -->
  <script src="http://localhost:8080/SPV/public/lib/jquery/jquery.min.js"></script>
  <script src="http://localhost:8080/SPV/public/lib/bootstrap/js/bootstrap.min.js"></script>
  <!--BACKSTRETCH-->
  <!-- You can use an image of whatever size. This script will stretch to fit in any screen size.-->
  <script type="text/javascript" src="http://localhost:8080/SPV/public/lib/jquery.backstretch.min.js"></script>
  <script>
    $.backstretch("http://localhost:8080/SPV/public/img/login-bg.jpg", {
      speed: 500
    });
  </script>

    <script src="http://localhost:8080/SPV/public/js/login/login.js"></script>

</body>

</html>




















